version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - fts5

formatters:
  enable:
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - revive

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
